server:
  port: 9095

spring:
  datasource:
    url: jdbc:mariadb://localhost:33061/Restaurant
    driver: org.mariadb.jdbc.Driver
    username: root
    password: example
    testWhileIdle: true
    validationQuery: SELECT 1

hibernate:
  id:
    new_generator_mappings: false









